### ISSUE TITLE
Migration from Bintray / JCenter to Sonatype / Maven Central

### ISSUE THREAD

**Issue by stswn** [ing-bank/scruid#110]
With beginning of May, Bintray service is going to be deprecated which means that we will not be able to publish Scruid anymore.

We have a possibility to publish it to Maven Central under ING project.

Apart from obvious changes, it will require small but breaking reorganization of the code:
We need to change artifact groupId and root package from `ing.wbaa.scruid` to `com.ing.wbaa.scruid`.

To avoid confusion new minor version of Scruid should be released without any functional changes from `2.4.0` and published under new groupId to ING project in Maven Central.

**Comment by anskarl** [comment]
it's fine by me as long as the project will remain open source with Apache 2.0 license.

**Comment by anskarl** [comment]
Project Github actions to compile, test and build scruid fail with the following error:
![Screenshot 2021-05-24 at 10 15 43 PM](https://user-images.githubusercontent.com/7415349/119398101-c001bb80-bcdf-11eb-97b9-9e6c09a33cb0.png)
I had a the same error initially in GH-111. Commit ef98646  of GH-111 fixes that problem by changing the exposed port numbers docker-compose.
