### ISSUE TITLE
TimeoutException on big payloads

### ISSUE THREAD

**Issue by vkorchik** [ing-bank/scruid#16]
Hi, guys
When fetсhing a big json from druid, Scruid is unable to parse it in 5 seconds (hardcoded [here](https://github.com/ing-bank/scruid/blob/5b13467d6ec900186fad77c500d9bd302a41907e/src/main/scala/ing/wbaa/druid/DruidClient.scala#L53)), and fails. 
I see you have a config entry `readTimeout`, I think it was supposed to be in this place instead of hardcode. Now it's just a config entry doing nothing.

Hope it will be fixed soon.
Thank you.

**Comment by Fokko** [comment]
Thanks @vkorchik for reaching out. @mrooding just pushed a patch that makes the response timeout configurable. If there are any further issues, please let me know. Cheers!
