### ISSUE TITLE
SBT version 1.x.x

### ISSUE THREAD

**Issue by vkorchik** [ing-bank/scruid#20]
Hey guys.

Are there any plans to bump sbt version to 1.x.x? All plugins support sbt 1.x.x, so there should be no problems.

**Comment by Fokko** [comment]
Hi @vkorchik, currently it isn't on the roadmap, but I don't have anything against upgrading SBT. @krisgeus any thoughts?

**Comment by krisgeus** [comment]
If indeed all the current plugins support it and the release  can be made with sbt 1 I'm perfectly ok with it

**Comment by vkorchik** [comment]
@Fokko, I don't know if this is a big deal, but [this is](https://stackoverflow.com/questions/44317384/sbt-error-failed-to-construct-terminal-falling-back-to-unsupported?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa) what I have now. As you can see in the answer, this bug was fixed in `0.13.16` (and scruid has `0.13.15`). (To run tests I needed to change project's `build.properties` to use newer version, in my case `1.1.5`)

I saw this error first when upgraded to Ubuntu 18.04. On the other hand everything's ok on MacOS. 

Apart from that, I think it is always better to keep up with the newest version of dependencies.

**Comment by Fokko** [comment]
Yesterday evening I've build your branch on OSX and it worked fine. Not sure what OS the CI is running, but it seems to work at CircleCI as well. Like @krisgeus said, I'm also perfectly fine with upgrading to 1.x.x. And I agree, should keep up with the dependencies.

Cheers, Fokko

**Comment by Fokko** [comment]
@vkorchik Master is now at SBT 1.1.5.
