### ISSUE TITLE
Scruid 1.1.0 for scala 2.12

### ISSUE THREAD

**Issue by vkorchik** [ing-bank/scruid#25]
Hi, 
it seems like scruid 1.1.0 was not released for scala 2.12.

I will appreciate the soonest upgrade very much.

**Comment by bjgbeelen** [comment]
Sorry my bad, have to get used to this cross publishing....

**Comment by vkorchik** [comment]
@bjgbeelen, i thought that maybe it was made by accident, but had no other way to contact you, except creating the issue ;)

**Comment by bjgbeelen** [comment]
Turns out couldn't even compile to 2.12.6, so reverted to 2.12.5 and made a new release (v1.1.1)
