### ISSUE TITLE
Move to CircleCI 2.0

### ISSUE THREAD

**Issue by Fokko** [ing-bank/scruid#27]
Eventually we have to move to Circle CI version 2.0, since 1.x won't be supported after August 31.

**Comment by bjgbeelen** [comment]
I spent 3 houts yesterday to migrate to circleci 2.0. But it is still failing :( getting OOMs. I understand we get 4gb of ram. I constrained the sbt mem usage, which seemed necessary. Once running the tests succeeded i tried also spinning up the docker druid container but the combination again failed

The worming branch Is *upgrade-to-circleci2*

**Comment by bjgbeelen** [comment]
This is fixed now
