### ISSUE TITLE
Scruid Logo

### ISSUE THREAD

**Issue by bjgbeelen** [ing-bank/scruid#40]
Recently I made a slide with logos of technologies I worked with and realized that Scruid doesn't have a logo yet. 

Taking both technologies and the 'wordplay' into account i came up with this idea (quick sketch)

![image](https://user-images.githubusercontent.com/8626944/48942267-0c0cf300-ef1f-11e8-8253-8b5de4001e4e.jpg)

This takes part of the Druid logo together with Scala's red color to form a particular hand gesture 😝 

Any other suggestions?
I'm also not sure to what extent it would be allowed to link to (a part of) the Druid logo

**Comment by bjgbeelen** [comment]
![scruid-sketch2](https://user-images.githubusercontent.com/8626944/48952454-8438e000-ef42-11e8-8cee-5c6003fb1250.jpg)

A less offensive alternative (rough sketch)

**Comment by bjgbeelen** [comment]
![scruid-sketch3](https://user-images.githubusercontent.com/8626944/48952658-38d30180-ef43-11e8-94c9-3e71a024050a.jpg)

Another rough sketch

**Comment by anskarl** [comment]
How about something like this?
![scruid](https://user-images.githubusercontent.com/7415349/62414314-6c157680-b622-11e9-977c-1d96662f8b37.png)

**Comment by bjgbeelen** [comment]
Cool, @anskarl nice addition! I personally like it when you can have a logo that also works without text. I had some time today to work out one of my previous sketches into a more complete one. Current versions are in SVG, below's copies are of less quality in PNG. 

I think just the logo without `Scruid` text would work as well.

![scruid-with-tagline (2)](https://user-images.githubusercontent.com/8626944/62424679-6d9e7780-b6d2-11e9-978a-8f0ab5a19182.png)

![scruid-vertical (2)](https://user-images.githubusercontent.com/8626944/62424682-7131fe80-b6d2-11e9-8361-391e3d7289ed.png)

**Comment by anskarl** [comment]
wow! I like it!

**Comment by Fokko** [comment]
Awesome!

**Comment by bjgbeelen** [comment]
Hmm im wondering about the tagline I used. Should it actually be `a Scala client for Apache Druid` or something among those lines?
