### ISSUE TITLE
Upgrade circe to version 0.10.1

### ISSUE THREAD

**Issue by anskarl** [ing-bank/scruid#47]
Current version of scruid uses circe version 0.9.3, while the latest is 0.10.1.

Version 0.10.1 or circe resolves the issue of not having a public trait providing `java.time` that appeared in version 0.10.0 (for details, see https://github.com/circe/circe/issues/976). According to the release notes of 0.10.1, the `TimeInstances` trait or 0.9.x can be replaced with `JavaTimeDecoders` and `JavaTimeEncoders`.

**Comment by Fokko** [comment]
Merged, thanks @anskarl
