### ISSUE TITLE
Couldn't add dependency by sbt

### ISSUE THREAD

**Issue by KalumDog** [ing-bank/scruid#57]
by adding `libraryDependencies += "ing.wbaa.druid" %% "scruid" % "2.1.0"`

Get this error

(update) sbt.librarymanagement.ResolveException: unresolved dependency: ing.wbaa.druid#scruid_2.12;2.1.0: not found
[error] (ssExtractDependencies) sbt.librarymanagement.ResolveException: unresolved dependency: ing.wbaa.druid#scruid_2.12;2.1.0: not found

**Comment by Fokko** [comment]
It is at Maven central: https://mvnrepository.com/artifact/ing.wbaa.druid/scruid_2.11/2.1.0

Did you set your resolvers correctly?
