### ISSUE TITLE
Release for scala 2.11

### ISSUE THREAD

**Issue by ajtkulov** [ing-bank/scruid#7]
Any chance to release it for scala 2.11?

Yeah, I know 2.12 is modern. But I cannot easily upgrade to 2.12 cause of a lot of dependencies.

**Comment by silvestre-abruzzo** [comment]
The same for us. We work with spark and we are forced to stick to 2.11. Would be possible to release the last version for 2.11 ? Thank you

**Comment by asaitov** [comment]
:+1:
