### ISSUE TITLE
Implementation of Javascript aggregator for DQL

### ISSUE THREAD

**Issue by utk14** [ing-bank/scruid#72]
Hi I am working on the DQL and I am facing difficulty with how to implement the javascript aggregator for the druid query language.

**Comment by anskarl** [comment]
I've prepared an update in order add support for Javascript aggregators in Scruid.

To pass the tests, it requires a Druid server with Javascript support enabled. @Fokko I've made a PR in https://github.com/Fokko/docker-druid/pull/3 in order to have a docker image with Javascript support enabled.

**Comment by Fokko** [comment]
My pleasure @anskarl. Looking forward to the aggregator.

**Comment by utk14** [comment]
@anskarl Is there the implementation of javascript post aggregator for DQL?

**Comment by anskarl** [comment]
> @anskarl Is there the implementation of javascript post aggregator for DQL?

@utk14 the implementation is in the pull request https://github.com/ing-bank/scruid/pull/77 

An example can be found in docs https://github.com/anskarl/scruid/blob/feature/js_aggregation/docs/dql.md#javascript-aggregator

**Comment by utk14** [comment]
@anskarl If I am not wrong your PR is supposed to be the JavascriptAggregator..
I wanted to know whether there is any implementation for javascriptPostAggregator.

I want to implement something similar to Druid's javascript post aggregator (https://druid.apache.org/docs/latest/querying/post-aggregations.html):

```
{
  "type": "javascript",
  "name": "absPercent",
  "fieldNames": ["delta", "total"],
  "function": "function(delta, total) { return 100 * Math.abs(delta) / total; }"
}
```

**Comment by anskarl** [comment]
You are right @utk14, I've updated the PR with Javascript post-aggregator in DQL.

**Comment by utk14** [comment]
@anskarl Thanks for the help. Is your PR merged?

**Comment by anskarl** [comment]
I think the issue can be closed, since the corresponding PR has been merged to the master branch

**Comment by Fokko** [comment]
Thank you for the update @anskarl. By any chance @utk14, did you find an opportunity to test the aggregator?

**Comment by utk14** [comment]
@Fokko Yeah It worked perfectly.. Please let me know when will you release the maven dependency with the latest changes?

**Comment by Fokko** [comment]
Awesome, great to hear. @mmartina any plan for a release? :-)

**Comment by utk14** [comment]
Hi @Fokko any updates when you are planning to release the maven version?

**Comment by mmartina** [comment]
v2.3.0 released.
