### ISSUE TITLE
How to calculate the count distinct from the cardianality functionality of Druid in the druid query language (DQL)

### ISSUE THREAD

**Issue by utk14** [ing-bank/scruid#73]
Hi,
I was working on the generation of count distinct number for a particular metrics using DQL but  unable to implement cardinality functionality of the druid (https://druid.apache.org/docs/latest/querying/aggregations) into the scruid

**Comment by anskarl** [comment]
Hi @utk14 I've prepared a PR to add support for cardinality aggregation in Scruid

**Comment by utk14** [comment]
@anskarl Has your PR merged?

**Comment by anskarl** [comment]
@utk14 merged today
