### ISSUE TITLE
When will the maven dependency for the 2.2.1-SNAPSHOT version be published?

### ISSUE THREAD

**Issue by utk14** [ing-bank/scruid#76]

**Comment by bjgbeelen** [comment]
We’re still working on some open PRs, I think it makes sense to await those to be merged before doing a new release. Hang in there 🙂

If you are really in a hurry you could always do a `publish-local` of the current `master` branch and use that jar in the meantime

**Comment by Fokko** [comment]
Like Bas mentioned, we don't publish any snapshot releases. You can easily publish it locally using `sbt publishLocal`. More info here: https://www.scala-sbt.org/1.x/docs/Publishing.html#Publishing+Locally
