### ISSUE TITLE
Release v2.4.0

### ISSUE THREAD

**Issue by anskarl** [ing-bank/scruid#97]
Since v2.3.0, an outline of the new features and changes is given below:

 - Include all Dockerfiles in the project and switch to GitHub Actions and Packages (GH-84)
 - Scan and Search queries (GH-83, GH-85, GH-89 and GH-92)
 - Additional Float and String aggregators (GH-86)
 - Support for Druid SQL (GH-90 and GH-91)
 - Use `requestInterceptor` in health checks (GH-93 and GH-94)
 - Use `com.typesafe.scala-logging` instead of using `slf4j` directly (GH-95)
 - Expand "tests" section in README file (GH-96)

Is it possible to proceed with a new release of Scruid library (v2.4.0)?

:)

**Comment by barend** [comment]
If it were released as-is I would be okay with that, but there are a couple of things I would like to fix before the release:

- I can see in the build output that I've somehow managed to log the stack trace with health check failures, despite my intention not to. Probably a difference between raw SLF4J and Typesafe-Logging that I overlooked. I think the logging is too noisy there.
- I am a little bit bothered by the "upstream failed / abrupt termination" warnings in the unit test suite. If we can do a clean stop in the tearDown handler, there won't be that "boy who cried wolf effect" if we ever introduce a _real_ warning

**Comment by barend** [comment]
I'll create a PR with some pre release housekeeping

**Comment by barend** [comment]
Pull request ready for review. Resolving those Akka shutdown warnings turns out not to be really feasibly. There are tons of issues mentioning them, which are [unresolved](https://github.com/akka/akka/issues/18747) since 2015 or so. That suggests it's a tough one.

**Comment by anskarl** [comment]
Indeed it's a an old and unresolved issue regarding the Akka shutdown error message. The error message in Scruid is fired from the logging of cachedHostConnectionPool Flow. When, for example, comment out the `.log("scruid-load-balancer", _ => s"Sending query to ${queryHost.host}:${queryHost.port}")` part in `DruidAdvancedHttpClient.scala` then the error message is not exposed. 

I think it is safe leave it unchanged. Perhaps in a future release of Akka it may be resolved.

**Comment by mmartina** [comment]
Hi Anastasios, we expect to complete release 2.4.0 before the end of this week.
best regards, Marcus Martina

**Comment by mmartina** [comment]
released :)
